services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MoveElevator\Styleguide\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'
